seq-cifar10-224:
  lr: 1e-3
  model: ovor
  optim_mom: 0.9
  optimizer: adam
  batch_size: 16
  select: 10
  num_per_class: 160
seq-cifar100-224:
  lr: 1e-3
  model: ovor
  optim_mom: 0.9
  optimizer: adam
  batch_size: 16
  select: 10
  num_per_class: 160
seq-imagenet-r:
  lr: 1e-3
  model: ovor
  optim_mom: 0.9
  optimizer: adam
  batch_size: 16
  select: 10
  num_per_class: 160
seq-cars196:
  lr: 1e-3
  model: ovor
  optim_mom: 0.9
  optimizer: adam
  batch_size: 16
  select: 4
  num_per_class: 60
  cov: 0.1
seq-cub200:
  lr: 1e-3
  model: ovor
  optim_mom: 0.9
  optimizer: adam
  batch_size: 16
  select: 4
  num_per_class: 60
  cov: 0.1
seq-eurosat-rgb:
  lr: 1e-3
  model: ovor
  optim_mom: 0.9
  optimizer: adam
  batch_size: 16
  select: 10
  num_per_class: 160
seq-resisc45:
  lr: 1e-3
  model: ovor
  optim_mom: 0.9
  optimizer: adam
  batch_size: 16
  select: 10
  num_per_class: 160
seq-chestx:
  lr: 1e-3
  model: ovor
  optim_mom: 0.9
  optimizer: adam
  batch_size: 16
  select: 10
  num_per_class: 160
seq-isic:
  lr: 1e-3
  model: ovor
  optim_mom: 0.9
  optimizer: adam
  batch_size: 16
  select: 10
  num_per_class: 160
seq-cropdisease:
  lr: 1e-3
  model: ovor
  optim_mom: 0.9
  optimizer: adam
  batch_size: 16
  select: 10
  num_per_class: 160